version: '3'

services:
  #reverse-proxy:
  #  image: traefik # The official Traefik docker image
  #  command: --api --docker.exposedbydefault=false # Enables the web UI and tells Træfik to listen to docker, without exposing by default
  #  ports:
  #    - "80:80"     # The HTTP port
  #    - "8080:8080" # The Web UI (enabled by --api)
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  db:
    image: mysql:5
    restart: always
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_PORT
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d/
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
  #processing:
  #  build:
  #    dockerfile: Dockerfile
  #    context: processing
  #  restart: unless-stopped
  #  env_file: processing/.env
  #  volumes:
  #    - "./processing:/app"
  #  environment:
  #    - DB_HOST=${DB_HOST}
  #    - DB_NAME=${DB_NAME}
  #    - DB_USER=${DB_USER}
  #    - DB_PASSWORD=${DB_PASSWORD}
  #    - EMAIL_FROM=${EMAIL_FROM}
  #    - EMAIL_PASSWORD=${EMAIL_PASSWORD}
  #    - EMAIL_TO=${EMAIL_TO}
  #    - BING_DIRECTORY=${BING_DIRECTORY}
  #    - BING_API_KEYS=${BING_API_KEYS}
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.frontend.rule=Host:app.test.localhost.tv"
   # depends_on:
   #   - db
  api:
    build:
      dockerfile: Dockerfile
      context: api
    restart: unless-stopped
    env_file: api/.env
    volumes:
      - "./api:/app"
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_TO=${EMAIL_TO}
      - BING_DIRECTORY=${BING_DIRECTORY}
      - BING_API_KEYS=${BING_API_KEYS}
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.frontend.rule=Host:app.test.localhost.tv"
    depends_on:
      - db
  app:
    build:
      dockerfile: Dockerfile
      context: site/irishhouseprices
    restart: unless-stopped
    volumes:
      - "./site/irishhouseprices:/app"
    ports:
      - "3000:3000"
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.frontend.rule=Host:app.test.localhost.tv"
    depends_on:
      - db